# Generated by Django 3.1.6 on 2021-02-07 08:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('is_recommended', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отел',
                'verbose_name_plural': 'Отели',
            },
        ),
    ]
