# Generated by Django 3.1.6 on 2021-02-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
