# Generated by Django 3.1.6 on 2021-03-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210214_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('enter_date', models.DateField(verbose_name='Дата заезда')),
                ('leave_date', models.DateField(verbose_name='Дата выезда')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('adult', models.PositiveSmallIntegerField(verbose_name='Взрослые')),
                ('child', models.PositiveSmallIntegerField(verbose_name='Дети')),
                ('room', models.PositiveSmallIntegerField(verbose_name='Комнаты')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hotel', verbose_name='Отел')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
