# Generated by Django 3.1.6 on 2021-03-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
