# Generated by Django 3.1.6 on 2021-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enter_date',
            field=models.DateField(null=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='leave_date',
            field=models.DateField(null=True, verbose_name='Дата выезда'),
        ),
    ]
