# Generated by Django 3.1.6 on 2021-03-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210324_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('chat_id', models.CharField(max_length=100, verbose_name='Чат ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активный?')),
            ],
            options={
                'verbose_name': 'Телеграм Чат',
                'verbose_name_plural': 'Телеграм Чат',
            },
        ),
    ]
