# Generated by Django 3.1.6 on 2021-03-27 05:09

import ckeditor_uploader.fields
from django.db import migrations, models
import main.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_telegramchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
            },
            bases=(main.mixins.ImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OurContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наши Контакты',
            },
            bases=(main.mixins.ImageMixin, models.Model),
        ),
    ]
