# Generated by Django 3.1.6 on 2021-04-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutus_ourcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_set', to='main.region', verbose_name='Регион'),
        ),
    ]
